version: '1'
services:
  mutants-api:
    build:
      context: .
      dockerfile: mutants-api.docker.yaml
    ports:
      - 8080:8080
    depends_on:
      - mysqldatabase
    networks:
      mutants-network:
        aliases:
          - mutants-network-api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldatabase:3306/mutants?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
  mysqldatabase:
    image: mysql:8.0.14
    networks:
      mutants-network:
        aliases:
          - mutants-network-database
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=mutants
      - MYSQL_ONETIME_PASSWORD=true
networks:
  mutants-network: