version : '2'
services:
  mutantsapi:
    build:
      context: .
      dockerfile: simple-mutants.docker.yaml
    ports:
      - "8080:8080"
    networks:
      - net-spring-db
    volumes:
      - .:/MutantsApi
    depends_on:
      - mysqldbserver
  mysqldbserver:
    build:
      context: .
      dockerfile: mysql.dockerfile.yaml
    ports:
      - "3306:3306"
    networks:
      - net-spring-db
    environment:
      MYSQL_DATABASE: mutants
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    container_name: mysqldbserver
networks:
  net-spring-db:
    driver: bridge